# 1. git clone (git-clone)
# 2. unit test goapp (golang-test)
# 3. code analysis - (sonarqube-scanner)
# 4. Trivy vulnerability scanning - docker image (trivy-scanner)
# 5. build and push docker image (kaniko)

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: complete-app-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: sonar-settings
    - name: registry-secret
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: 
        - name: subdirectory
          value: ""

    - name: unit-test-goapp
      taskRef:
        name: golang-test
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository
      params:
        - name: package
          value: github.com/tektoncd/pipeline
        - name: version
          value: "1.21.1"    

    - name: code-analysis
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - unit-test-goapp
      params:
        - name: SONAR_HOST_URL
          value: http://192.168.8.200:9000
        - name: SONAR_PROJECT_KEY
          value: 11-12-go-test-app
        - name: SONAR_ORGANIZATION
          value: ice
        - name: SONAR_PROJECT_TOKEN
          value: sqa_4ecb134715268da3583e6e0d16f6ee158ca580b7
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: sonar-settings
          workspace: sonar-settings    

    - name: build-docker-tar-image
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: registry-secret
      runAfter:
        - code-analysis
      params:
        - name: EXTRA_ARGS
          value: ["--no-push", "--tarPath", "image.tar"]
        - name: IMAGE
          value: "testbuild"

    - name: trivy-scan
      runAfter:
        - build-docker-tar-image
      taskRef:
        name: trivy-scanner
      params:
        - name: ARGS
          value: ["image", "--timeout", "15m", "--input"]
        - name: IMAGE_PATH
          value: "./image.tar"
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace

    - name: build-docker-image
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: registry-secret
      runAfter:
        - trivy-scan
      params:
        - name: IMAGE
          value: "registry.gitlab.com/sameeradamith/goapp:v1.9.1"       
