apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: frontend-cicd-
  labels:
    tekton.dev/pipeline: frontend-app-cicd
spec:
  serviceAccountName: gitlab-bot
  pipelineRef:
    name: frontend-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: go-app-pvc

    - name: sonar-settings
      persistentvolumeclaim:
        claimName: sonar-config-pvc
        
    - name: registry-secret
      secret:
        secretName: test-gitlab-secret

