# 1. git clone (git-clone)
# 2. install-dependencies (npm)
# 3. run-lint (Static code analysis)
## run-test
## validating/scan Docker image
# 4. build and push docker image (kaniko)

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: registry-secret
    - name: sonar-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value:
        - name: subdirectory
          value: ""

    - name: list-dir
      taskSpec:
        steps:
          - name: ls-repo-directory
            image: alpine
            command:
              - /bin/sh
            args:
              - '-c'
              - |
                cd workspace/output; ls; pwd;
      runAfter:
        - fetch-repository
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "docker.io/library/node:16.20.2-alpine3.18@sha256:72e89a86be58c922ed7b1475e5e6f151537676470695dd106521738b060e139d"
        - name: ARGS
          value:
            - clean-install
      runAfter:
        - fetch-repository

    - name: run-lint
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "docker.io/library/node:16.20.2-alpine3.18@sha256:72e89a86be58c922ed7b1475e5e6f151537676470695dd106521738b060e139d"
        - name: ARGS
          value:
            - run
            - lint
      runAfter:
        - install-dependencies

    - name: code-analysis
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - run-lint
      params:
        - name: SONAR_HOST_URL
          value: http://192.168.1.3:9000
        - name: SONAR_PROJECT_KEY
          value: angular-app
        - name: SONAR_ORGANIZATION
          value: ice
        - name: SONAR_PROJECT_TOKEN
          value: sqa_4ecb134715268da3583e6e0d16f6ee158ca580b7
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: sonar-settings
          workspace: sonar-settings 
